%% wxrecordvideo
 % Record video using the camera Logitech (USB Video Device)
 % JL Alatorre-Warren

%% Initial setup

% Get relevant information from wxtmaze
[pathRoot,...
 pathData,...
 pathRois,...
 pathTrials,...
 pathTrialList,...
 structureOfTrials,...
 listOfedTrials,...
 trialName,...
 pathCurrentTrial,...
 mouseName,...
 experimentName,...
 timestampVector,...
 dateString,...
 timeString] = wxlistentowxtmaze; %#ok<*ASGLU>

% Get the rest of the information
[~,...
 ~,...
 ~,...
 ~,...
 ~,...
 ~,...
 pathMouseName,...
 pathDateString,...
 pathExperimentName,...
 pathTimeString,...
 pathFlags,...
 pathSignals,...
 pathFrames] = wxcreatedirectories(timestampVector,... 
                                   mouseName,...
                                   dateString,...
                                   experimentName,...
                                   timeString);
                                 
% Load flag variables to be used in wxrecordvideo
optionSaveFrames = load([pathFlags '/' 'optionsaveframes.mat']);
optionSaveVideo  = load([pathFlags '/' 'optionsavevideo.mat' ]);
imageFormat      = load([pathFlags '/' 'imageformat.mat'     ]);

% Convert the loaded structures to variables with the same name
optionSaveFrames = optionSaveFrames.optionSaveFrames;
optionSaveVideo  = optionSaveVideo.optionSaveVideo;
imageFormat      = imageFormat.imageFormat;
                                  
% Send flag to wxtmaze
flagRecordVideoReady = true; %#ok<*NASGU>
save([pathFlags '/' 'flagrecordvideoready.mat'], 'flagRecordVideoReady');

%% Setup live preview

% Create axes control
handleToAxes = axes();

% Get the handle to the image
hImage = image(zeros(480,640,'uint8'));
hold off;
axis auto;
axis on;

% Set the property OuterPosition of the figure
set(gcf, 'Units', 'Pixels', 'OuterPosition', [1281 741 869 700]);

% Preview webcam Logitech
listOfWebcams = webcamlist;
cameraObject = webcam(listOfWebcams{1,1});
preview(cameraObject, hImage);

%% Save frames and record video

% Save frames if the user selected it in wxgui
if optionSaveFrames == 1

  % Track time
  tic

  % Save frames until flag sent from wxtmaze is found
  flagFound = false;
  while flagFound == false

    % Take snapshot
    currentFrame = snapshot(cameraObject); 

    % Save the data that is currently available the image format selected in wxgui   
    switch imageFormat
      
      case 'MATLAB'
        save([pathFrames     '/' ...
              'frame'        '_' ...
              mouseName      '_' ...
              experimentName '_' ...
              datestr(now,'yyyymmddHHMMSSFFF') '.mat'], ...
              'currentFrame');
      case 'JPEG'
        imwrite(currentFrame,[pathFrames     '/' ...
                              'frame'        '_' ...
                              mouseName      '_' ...
                              experimentName '_' ...
                              datestr(now,'yyyymmddHHMMSSFFF') '.jpg'],'jpg')
      case 'PNG'
        imwrite(currentFrame,[pathFrames     '/' ...
                              'frame'        '_' ...
                              mouseName      '_' ...
                              experimentName '_' ...
                              datestr(now,'yyyymmddHHMMSSFFF') '.png'])        
      case 'TIFF'
        imwrite(currentFrame,[pathFrames     '/' ...
                              'frame'        '_' ...
                              mouseName      '_' ...
                              experimentName '_' ...
                              datestr(now,'yyyymmddHHMMSSFFF') '.tif'])
                            
    end
    
    % Currently, it is necessary to save the frames in MATLAB format to
    % produce a video
    if (strcmp(imageFormat, 'MATLAB') == 0) && (optionSaveVideo == 1)
      save([pathFrames     '/' ...
            'frame'        '_' ...
            mouseName      '_' ...
            experimentName '_' ...
            datestr(now,'yyyymmddHHMMSSFFF') '.mat'], ...
            'currentFrame');    
    end

    % Search flag and break the loop if found
    flagSequenceCompleted = exist([pathFlags '/' 'flagsequencecompleted.mat'],'file');  
    if (flagSequenceCompleted == 2)
      flagFound = true;
    end

    toc
  end
  clear currentFrame

end

% If the user decided in wxgui to produce a video, call wxproducevideo once
% the T-maze has been completed (flag has been found)
if optionSaveVideo == 1
  wxproducevideo(pathFrames)
end

% Close MATLAB session
exit